### ISSUE TITLE
Wrong output file directory when specifying a different one

### ISSUE THREAD

**Issue by renA21** [emiyl/nxDumpMerger#1]
When specifying a different directory for the output file, the merged dump file doesn't get stored to the specified directory. Instead, it gets stored outside of the specified directory with the name of the merged dump renamed containing the directory's name as the prefix.

![image](https://user-images.githubusercontent.com/44066520/99920615-52ea7a80-2cea-11eb-90d3-ec0299ad364c.png)

**Comment by emiyl** [comment]
fixed in commit [3706c34 ](https://github.com/emiyl/nxDumpMerger/commit/3706c34c69977a7a4981b502ae101d4d438c460e)
