### ISSUE TITLE
XCI Dump creates 4 files but I can't merge them together

### ISSUE THREAD

**Issue by Leahcimjs** [emiyl/nxDumpMerger#4]
I Tried dumping a game from a cartridge to the sd card but it split into 4 files. The guide I'm following accounts for this but the software they recommended doesn't seem to work. It only sees the first file but tells me it will automatically recognize the others, which it does because the progress bar says 1/4 (because there's 4 files, .xc0, .xc1, .xc2, and .xc3) But once it finishes with the first .xc0 file it doesn't continue to the other 3, what am I doing wrong?

**Comment by hassfam** [comment]
Same here, having this issue with Breath of the Wild. I tried manually putting in the path file, but still didn't work.

**Comment by Leahcimjs** [comment]
I remember what the problem was and how to fix it! It's probably because the files are on your switches sd card still right? You need to copy them over to your desktop before you begin to merge the files. Hopefully that fixes the issue you're having!
