### ISSUE TITLE
NSP merge results in gametitle(titleID) (BASE).nsp.nsp

### ISSUE THREAD

**Issue by BUts69** [emiyl/nxDumpMerger#7]
Trying to merge a game (BASE).nsp that I dumped from my switch as a NSP with the python script on Linux. File was dumped into 4 files (00, 01, 02,& 03) and I moved them to my system before starting the merge. Once merge is finished, the output file has the .nsp file extension in the file name followed by .nsp [ex. Xenoblade Chronicles 3 v0 (16-digit number) (BASE).nsp.nsp] Will renaming the output file after it’s been merged alter its ability to be read? Or do I need to rename the output before merging the dump files?

**Comment by emiyl** [comment]
Renaming the output file will have no effect on the contents of the file.
